/*
 * 运营商业务API接口
 * 运营商业务API接口平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package xin.juhe.operator.api;

import xin.juhe.operator.ApiException;
import xin.juhe.operator.model.HttpEntity;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OauthApi
 */
@Ignore
public class OauthApiTest {

    private final OauthApi api = new OauthApi();

    
    /**
     * 获取Token
     *
     * 获取Token
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTokenTest() throws ApiException {
        String clientId = null;
        String clientSecret = null;
        String response = api.getToken(clientId, clientSecret);

        // TODO: test validations
    }
    
    /**
     * 获取用户信息
     *
     * 获取用户信息
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserInfoTest() throws ApiException {
        HttpEntity response = api.getUserInfo();

        // TODO: test validations
    }
    
    /**
     * 获取用户信息
     *
     * 获取用户信息
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserInfo1Test() throws ApiException {
        HttpEntity response = api.getUserInfo1();

        // TODO: test validations
    }
    
}
